sudo: required
services:
  - docker

before_install:
  - docker build -t jeetondocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jeetondocker/react-test npm test

after_success:
  # log in to the docker CI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t jeetondocker/multi-client ./client
  - docker build -t jeetondocker/multi-nginx ./nginx
  - docker build -t jeetondocker/multi-server ./server
  - docker build -t jeetondocker/multi-worker ./worker
  # take those images and push to dockerhub 
  - docker push jeetondocker/multi-client
  - docker push jeetondocker/multi-nginx
  - docker push jeetondocker/multi-server
  - docker push jeetondocker/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-921840947608'
  bucket_path: 'docker-multi'
  on:
    branch_name: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY